=== Interes-Group/java-course-xsd/src/main/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xs3p.xsl"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           version="1.1.0">
    <xs:element name="persons">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="person" name="person" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="person">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="surname" type="xs:string"/>
            <xs:element name="national_id" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element type="address" name="address"/>
            <xs:element type="address" name="correspondence_address" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="address">
        <xs:sequence>
            <xs:element name="street" type="xs:string"/>
            <xs:element name="street_number" type="xs:string"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="postal_code" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Interes-Group/java-course-xsd/src/main/resources/person.xml
<?xml version="1.0" encoding="UTF-8"?>
<persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <person>
        <id>1</id>
        <name>Jozko</name>
        <surname>Mrkvicka</surname>
        <national_id>9310201234</national_id>
        <email>mrkvicka@stuba.sk</email>
        <address>
            <street>Ilkovicova</street>
            <street_number>3</street_number>
            <city>Bratislava</city>
            <postal_code>84105</postal_code>
        </address>
    </person>
    <person>
        <id>1</id>
        <name>Jozko</name>
        <surname>Mrkvicka</surname>
        <national_id>9310201234</national_id>
        <email>mrkvicka@stuba.sk</email>
        <address>
            <street>Ilkovicova</street>
            <street_number>3</street_number>
            <city>Bratislava</city>
            <postal_code>84105</postal_code>
        </address>
    </person>
</persons>
